function profile = get_physics_profile(profileName)
%GET_PHYSICS_PROFILE Resolve the mainline stage2/stage4 physics profile.

if nargin < 1 || strlength(string(profileName)) == 0
    profileName = 'harmonics_refine_mainline';
end
profileName = char(string(profileName));

switch profileName
    case 'harmonics_refine_mainline'
        profile = struct( ...
            'name', 'harmonics_refine_mainline', ...
            'description', 'Mainline fixed-study harmonic refinement physics baseline.', ...
            'materialCase', 'soft_matrix_hard_inclusion', ...
            'studyNeigs', 20, ...
            'studyShiftHz', 200, ...
            'studyShiftExpr', '200[Hz]', ...
            'baseParamOverrides', struct( ...
                'r0', '0.012[m]', ...
                'a1', 0.45, 'b1', 0, ...
                'a2', 0, 'b2', 0, ...
                'a3', 0, 'b3', 0, ...
                'a4', 0, 'b4', 0, ...
                'a5', 0, 'b5', 0 ...
            ), ...
            'baseParamNumeric', struct( ...
                'r0', 0.012, ...
                'a1', 0.45, 'b1', 0, ...
                'a2', 0, 'b2', 0, ...
                'a3', 0, 'b3', 0, ...
                'a4', 0, 'b4', 0, ...
                'a5', 0, 'b5', 0 ...
            ) ...
        );
    otherwise
        error('get_physics_profile:UnknownProfile', 'Unknown physics profile: %s', profileName);
end
end
