function profile = get_target_profile(profileName)
%GET_TARGET_PROFILE Resolve the mainline fixed-gap target profile.

if nargin < 1 || strlength(string(profileName)) == 0
    profileName = 'gap_band_3_4_mainline';
end
profileName = char(string(profileName));

switch profileName
    case 'gap_band_3_4_mainline'
        profile = struct( ...
            'name', 'gap_band_3_4_mainline', ...
            'description', 'Mainline fixed 3-4 band-gap target used by dataset/training/stage4.', ...
            'objectiveName', 'gap34_gain_Hz', ...
            'metricColumn', 'gap34_gain_Hz', ...
            'fixedGapBand', 3, ...
            'higherIsBetter', true ...
        );
    otherwise
        error('get_target_profile:UnknownProfile', 'Unknown target profile: %s', profileName);
end
end
