function baselineByPoint = evaluate_stage2_baseline_points(cfg, doeTable)
%EVALUATE_STAGE2_BASELINE_POINTS Compute or reuse the no-snake baseline for each DOE point.

baselineByPoint = load_saved_baseline(cfg);
processedIds = strings(0, 1);
if ~isempty(baselineByPoint)
    processedIds = string({baselineByPoint.point_id})';
end

for i = 1:height(doeTable)
    pointSpec = table_row_to_struct(doeTable(i, :));
    pointId = string(pointSpec.point_id);
    if any(processedIds == pointId)
        continue;
    end

    fprintf('Baseline point [%d/%d] %s\n', i, height(doeTable), pointId);
    sampleMeta = struct( ...
        'sample_id', string(sprintf('%s__baseline__%s', cfg.fourierId, pointId)), ...
        'candidate_id', string('baseline'), ...
        'shape_id', string('__baseline__'), ...
        'shape_family', string('baseline'), ...
        'candidate_role', string('baseline'), ...
        'shape_file', string('') ...
    );
    result = evaluate_stage2_case_internal(cfg, sampleMeta, pointSpec, struct());
    if ~result.solve_success
        error('evaluate_stage2_baseline_points:PointFailed', ...
            'Baseline point %s failed: %s', pointId, result.error_message);
    end

    baselineByPoint = append_baseline_row(baselineByPoint, result);
    processedIds(end + 1, 1) = pointId; %#ok<AGROW>
    save_baseline(cfg, baselineByPoint);
end

baselineByPoint = sort_baseline_by_point(doeTable, baselineByPoint);
save_baseline(cfg, baselineByPoint);
end

function baselineByPoint = load_saved_baseline(cfg)
baselineByPoint = struct([]);
if ~cfg.reuseBaselineByPoint || ~isfile(cfg.baselineByPointMat)
    return;
end
loaded = load(cfg.baselineByPointMat, 'baselineByPoint', 'configSignature');
if ~isfield(loaded, 'baselineByPoint') || ~isfield(loaded, 'configSignature')
    return;
end
if ~strcmp(string(loaded.configSignature), string(cfg.configSignature))
    return;
end
baselineByPoint = loaded.baselineByPoint;
if ~isempty(baselineByPoint)
    fprintf('Reusing baseline-by-point cache: %s\n', cfg.baselineByPointMat);
end
end

function baselineByPoint = append_baseline_row(baselineByPoint, result)
row = struct( ...
    'point_id', string(result.point_id), ...
    'a1', result.a1, ...
    'a2', result.a2, ...
    'b2', result.b2, ...
    'r0', result.r0, ...
    'sample_id', string(result.sample_id), ...
    'ref_gap_Hz', result.gap_target_Hz, ...
    'ref_gap_rel', result.gap_target_rel, ...
    'gap_lower_band', result.gap_lower_band, ...
    'gap_upper_band', result.gap_upper_band, ...
    'gap_center_freq', result.gap_center_freq, ...
    'solve_success', result.solve_success, ...
    'error_message', string(result.error_message) ...
);

if isempty(baselineByPoint)
    baselineByPoint = row;
else
    baselineByPoint(end + 1) = row; %#ok<AGROW>
end
end

function baselineByPoint = sort_baseline_by_point(doeTable, baselineByPoint)
if isempty(baselineByPoint)
    return;
end
pointOrder = string(doeTable.point_id);
currentIds = string({baselineByPoint.point_id})';
[~, loc] = ismember(pointOrder, currentIds);
loc = loc(loc > 0);
baselineByPoint = baselineByPoint(loc);
end

function save_baseline(cfg, baselineByPoint)
configSignature = cfg.configSignature; %#ok<NASGU>
save(cfg.baselineByPointMat, 'baselineByPoint', 'configSignature');
if isempty(baselineByPoint)
    prototype = struct( ...
        'point_id', string(""), ...
        'a1', NaN, ...
        'a2', NaN, ...
        'b2', NaN, ...
        'r0', NaN, ...
        'sample_id', string(""), ...
        'ref_gap_Hz', NaN, ...
        'ref_gap_rel', NaN, ...
        'gap_lower_band', NaN, ...
        'gap_upper_band', NaN, ...
        'gap_center_freq', NaN, ...
        'solve_success', false, ...
        'error_message', string("") ...
    );
    baselineTable = struct2table(prototype, 'AsArray', true);
    baselineTable(1, :) = [];
else
    baselineTable = struct2table(baselineByPoint, 'AsArray', true);
end
writetable(baselineTable, cfg.baselineByPointCsv);
end

function pointSpec = table_row_to_struct(rowTable)
pointSpec = struct( ...
    'point_id', char(string(rowTable.point_id(1))), ...
    'a1', double(rowTable.a1(1)), ...
    'a2', double(rowTable.a2(1)), ...
    'b2', double(rowTable.b2(1)), ...
    'r0', double(rowTable.r0(1)) ...
);
end
