function cfg = get_stage2_config()
%GET_STAGE2_CONFIG Centralized config for stage-2 Fourier robustness screening.
% Stage-2 keeps the trusted mother fixed, reuses stage-1 outputs to choose
% representative snake shapes, and evaluates local Fourier robustness via a
% sparse DOE over a1 / a2 / b2 / r0.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
outDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage2_fourier_robustness');
stage1Dir = fullfile(rootDir, 'data', 'comsol_batch', 'stage1_shape_screening');

cfg = struct();
cfg.rootDir = rootDir;
cfg.stage1Dir = stage1Dir;
cfg.shapeDir = fullfile(rootDir, 'data', 'shape_contours');
cfg.outDir = outDir;
cfg.tbl1Dir = fullfile(outDir, 'tbl1_exports');
cfg.modelsDir = fullfile(outDir, 'models');
cfg.logsDir = fullfile(outDir, 'logs');
cfg.plotDir = fullfile(outDir, 'plots');
cfg.bandPlotDir = fullfile(cfg.plotDir, 'band_diagrams');

cfg.stage1SummaryCsv = fullfile(stage1Dir, 'stage1_summary_by_gap_gain.csv');
cfg.candidateManifestCsv = fullfile(outDir, 'stage2_candidate_manifest.csv');
cfg.doeManifestCsv = fullfile(outDir, 'stage2_doe_manifest.csv');
cfg.baselineByPointMat = fullfile(outDir, 'baseline_by_point.mat');
cfg.baselineByPointCsv = fullfile(outDir, 'baseline_by_point.csv');
cfg.resultsMat = fullfile(outDir, 'stage2_results.mat');
cfg.resultsCsv = fullfile(outDir, 'stage2_results.csv');
cfg.shapeSummaryCsv = fullfile(outDir, 'stage2_shape_summary.csv');
cfg.pointSummaryCsv = fullfile(outDir, 'stage2_point_summary.csv');

cfg.fourierId = 'stage2_local_fourier_v1';
cfg.materialCase = 'soft_matrix_hard_inclusion';
cfg.studyPName = {'k'};
cfg.studyPListArr = {'range(0,3/(N-1),3)'};
cfg.studyPUnit = {''};
cfg.studySweepType = 'filled';
cfg.studyNeigs = 20;
cfg.studyShiftHz = 200;
cfg.studyShiftExpr = '200[Hz]';

cfg.baseParamOverrides = struct( ...
    'r0', '0.012[m]', ...
    'a1', 0.45, 'b1', 0, ...
    'a2', 0, 'b2', 0, ...
    'a3', 0, 'b3', 0, ...
    'a4', 0, 'b4', 0, ...
    'a5', 0, 'b5', 0 ...
);
cfg.baseParamNumeric = struct( ...
    'r0', 0.012, ...
    'a1', 0.45, 'b1', 0, ...
    'a2', 0, 'b2', 0, ...
    'a3', 0, 'b3', 0, ...
    'a4', 0, 'b4', 0, ...
    'a5', 0, 'b5', 0 ...
);

cfg.candidateRoleCounts = struct( ...
    'strong_positive', 8, ...
    'weak_positive', 2, ...
    'negative', 2 ...
);
cfg.negativeSelectionMode = 'most_negative';
cfg.familyPattern = '^(ep\d+)';

cfg.saveModel = false;
cfg.enableBandPlots = false;
cfg.pythonCmd = 'python';
cfg.reuseBaselineByPoint = true;
cfg.positiveGapThresholdHz = 0;
cfg.contactTol = 2e-4;
cfg.contactSampleCount = 1440;
cfg.minExpectedDomains = 2;
cfg.tinyFragmentDomainThreshold = 3;

cfg.resultFieldOrder = { ...
    'sample_id', ...
    'candidate_id', ...
    'shape_id', ...
    'shape_family', ...
    'candidate_role', ...
    'point_id', ...
    'a1', ...
    'a2', ...
    'b2', ...
    'r0', ...
    'shift', ...
    'neigs', ...
    'material_case', ...
    'geometry_valid', ...
    'contact_valid', ...
    'contact_length', ...
    'n_domains', ...
    'has_tiny_fragments', ...
    'solve_success', ...
    'gap_target_Hz', ...
    'gap_target_rel', ...
    'gap_lower_band', ...
    'gap_upper_band', ...
    'gap_center_freq', ...
    'ref_gap_Hz', ...
    'ref_gap_rel', ...
    'gap_gain_Hz', ...
    'gap_gain_rel', ...
    'error_message' ...
};

cfg.candidateManifestFieldOrder = { ...
    'candidate_id', ...
    'shape_id', ...
    'shape_file', ...
    'shape_family', ...
    'candidate_role', ...
    'stage1_gap_gain_Hz', ...
    'stage1_gap_target_Hz', ...
    'stage1_candidate_tier', ...
    'family_duplicate' ...
};

cfg.doeFieldOrder = {'point_id', 'a1', 'a2', 'b2', 'r0'};

cfg.configSignature = strjoin({ ...
    cfg.fourierId, ...
    sprintf('a1=%.12g', cfg.baseParamNumeric.a1), ...
    sprintf('a2=%.12g', cfg.baseParamNumeric.a2), ...
    sprintf('b2=%.12g', cfg.baseParamNumeric.b2), ...
    sprintf('r0=%.12g', cfg.baseParamNumeric.r0), ...
    sprintf('shift=%.12g', cfg.studyShiftHz), ...
    sprintf('neigs=%d', cfg.studyNeigs), ...
    cfg.materialCase ...
}, ';');

ensure_dir(cfg.outDir);
ensure_dir(cfg.tbl1Dir);
ensure_dir(cfg.logsDir);
ensure_dir(cfg.plotDir);
if cfg.saveModel
    ensure_dir(cfg.modelsDir);
end
end

function ensure_dir(pathStr)
if ~exist(pathStr, 'dir')
    mkdir(pathStr);
end
end
