function baselineByPoint = evaluate_stage2_gapdiversity_baseline_points(cfg, doeTable)
%EVALUATE_STAGE2_GAPDIVERSITY_BASELINE_POINTS Compute or reuse the no-snake baseline for each exploration point.

baselineByPoint = load_saved_baseline(cfg);
processedIds = strings(0, 1);
if ~isempty(baselineByPoint)
    processedIds = string({baselineByPoint.point_id})';
end

for i = 1:height(doeTable)
    pointSpec = table_row_to_struct(doeTable(i, :));
    pointId = string(pointSpec.point_id);
    if any(processedIds == pointId)
        continue;
    end

    fprintf('Baseline point [%d/%d] %s\n', i, height(doeTable), pointId);
    sampleMeta = struct( ...
        'sample_id', string(sprintf('%s__baseline__%s', cfg.fourierId, pointId)), ...
        'candidate_id', string('baseline'), ...
        'shape_id', string('__baseline__'), ...
        'shape_family', string('baseline'), ...
        'candidate_role', string('baseline'), ...
        'shape_file', string('') ...
    );
    result = evaluate_stage2_gapdiversity_case_internal(cfg, sampleMeta, pointSpec, struct());
    if ~result.solve_success
        error('evaluate_stage2_gapdiversity_baseline_points:PointFailed', 'Baseline point %s failed: %s', pointId, result.error_message);
    end

    baselineByPoint = append_baseline_row(baselineByPoint, result);
    processedIds(end + 1, 1) = pointId; %#ok<AGROW>
    save_baseline(cfg, baselineByPoint);
end

baselineByPoint = sort_baseline_by_point(doeTable, baselineByPoint);
save_baseline(cfg, baselineByPoint);
end

function baselineByPoint = load_saved_baseline(cfg)
baselineByPoint = struct([]);
if ~cfg.reuseBaselineByPoint || ~isfile(cfg.baselineByPointMat), return; end
loaded = load(cfg.baselineByPointMat, 'baselineByPoint', 'configSignature');
if ~isfield(loaded, 'baselineByPoint') || ~isfield(loaded, 'configSignature'), return; end
if ~strcmp(string(loaded.configSignature), string(cfg.configSignature)), return; end
baselineByPoint = loaded.baselineByPoint;
if ~isempty(baselineByPoint)
    fprintf('Reusing baseline-by-point cache: %s\n', cfg.baselineByPointMat);
end
end

function baselineByPoint = append_baseline_row(baselineByPoint, result)
row = struct( ...
    'point_id', string(result.point_id), ...
    'sample_id', string(result.sample_id), ...
    'ref_gap_Hz', result.gap_target_Hz, ...
    'ref_gap_rel', result.gap_target_rel, ...
    'gap_lower_band', result.gap_lower_band, ...
    'gap_upper_band', result.gap_upper_band, ...
    'gap_center_freq', result.gap_center_freq, ...
    'solve_success', result.solve_success, ...
    'error_message', string(result.error_message) ...
);
for name = {'r0','a1','b1','a2','b2','a3','b3','a4','b4','a5','b5','A1','phi1','A2','phi2','A3','phi3','A4','phi4','A5','phi5','sumA','deriv_budget','min_radius_est','max_radius_est','max_abs_amp_slope','guardrail_pass'}
    key = char(name{1});
    row.(key) = result.(key);
end

if isempty(baselineByPoint)
    baselineByPoint = row;
else
    baselineByPoint(end + 1) = row; %#ok<AGROW>
end
end

function baselineByPoint = sort_baseline_by_point(doeTable, baselineByPoint)
if isempty(baselineByPoint), return; end
pointOrder = string(doeTable.point_id);
currentIds = string({baselineByPoint.point_id})';
[~, loc] = ismember(pointOrder, currentIds);
loc = loc(loc > 0);
baselineByPoint = baselineByPoint(loc);
end

function save_baseline(cfg, baselineByPoint)
configSignature = cfg.configSignature; %#ok<NASGU>
save(cfg.baselineByPointMat, 'baselineByPoint', 'configSignature');
if isempty(baselineByPoint)
    baselineTable = struct2table(make_empty_baseline_row(), 'AsArray', true);
    baselineTable(1, :) = [];
else
    baselineTable = struct2table(baselineByPoint, 'AsArray', true);
end
writetable(baselineTable, cfg.baselineByPointCsv);
end

function row = make_empty_baseline_row()
row = struct( ...
    'point_id', string(""), ...
    'sample_id', string(""), ...
    'ref_gap_Hz', NaN, ...
    'ref_gap_rel', NaN, ...
    'gap_lower_band', NaN, ...
    'gap_upper_band', NaN, ...
    'gap_center_freq', NaN, ...
    'solve_success', false, ...
    'error_message', string(""), ...
    'r0', NaN, ...
    'a1', NaN, 'b1', NaN, ...
    'a2', NaN, 'b2', NaN, ...
    'a3', NaN, 'b3', NaN, ...
    'a4', NaN, 'b4', NaN, ...
    'a5', NaN, 'b5', NaN, ...
    'A1', NaN, 'phi1', NaN, ...
    'A2', NaN, 'phi2', NaN, ...
    'A3', NaN, 'phi3', NaN, ...
    'A4', NaN, 'phi4', NaN, ...
    'A5', NaN, 'phi5', NaN, ...
    'sumA', NaN, ...
    'deriv_budget', NaN, ...
    'min_radius_est', NaN, ...
    'max_radius_est', NaN, ...
    'max_abs_amp_slope', NaN, ...
    'guardrail_pass', false ...
);
end

function pointSpec = table_row_to_struct(rowTable)
pointSpec = struct();
for name = rowTable.Properties.VariableNames
    key = char(name{1});
    value = rowTable.(key)(1);
    if isstring(value)
        pointSpec.(key) = char(value);
    elseif islogical(value)
        pointSpec.(key) = logical(value);
    else
        pointSpec.(key) = double(value);
    end
end
end
