function cfg = get_stage2_gapdiversity_config()
%GET_STAGE2_GAPDIVERSITY_CONFIG Exploration config for escaping the 3-4-dominant basin.
% This line samples Fourier boundaries in amplitude/phase space with
% explicit guardrails on radius positivity and boundary roughness.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
outDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage2_gapdiversity_exploration_v1');
stage1Dir = fullfile(rootDir, 'data', 'comsol_batch', 'stage1_shape_screening');

cfg = struct();
cfg.rootDir = rootDir;
cfg.stage1Dir = stage1Dir;
cfg.shapeDir = fullfile(rootDir, 'data', 'shape_contours');
cfg.outDir = outDir;
cfg.tbl1Dir = fullfile(outDir, 'tbl1_exports');
cfg.modelsDir = fullfile(outDir, 'models');
cfg.logsDir = fullfile(outDir, 'logs');
cfg.plotDir = fullfile(outDir, 'plots');
cfg.bandPlotDir = fullfile(cfg.plotDir, 'band_diagrams');

cfg.stage1SummaryCsv = fullfile(stage1Dir, 'stage1_summary_by_gap_gain.csv');
cfg.candidateManifestCsv = fullfile(outDir, 'stage2_gapdiversity_candidate_manifest.csv');
cfg.doeManifestCsv = fullfile(outDir, 'stage2_gapdiversity_doe_manifest.csv');
cfg.baselineByPointMat = fullfile(outDir, 'baseline_by_point.mat');
cfg.baselineByPointCsv = fullfile(outDir, 'baseline_by_point.csv');
cfg.resultsMat = fullfile(outDir, 'stage2_gapdiversity_results.mat');
cfg.resultsCsv = fullfile(outDir, 'stage2_gapdiversity_results.csv');
cfg.shapeSummaryCsv = fullfile(outDir, 'stage2_gapdiversity_shape_summary.csv');
cfg.pointSummaryCsv = fullfile(outDir, 'stage2_gapdiversity_point_summary.csv');

cfg.fourierId = 'stage2_gapdiversity_exploration_v1';
cfg.materialProfile = 'baseline_soft_hard';
cfg = apply_material_profile_to_config(cfg);
cfg.studyPName = {'k'};
cfg.studyPListArr = {'range(0,3/(N-1),3)'};
cfg.studyPUnit = {''};
cfg.studySweepType = 'filled';
cfg.studyNeigs = 20;
cfg.studyShiftHz = 200;
cfg.studyShiftExpr = '200[Hz]';

cfg.baseParamOverrides = struct( ...
    'r0', '0.012[m]', ...
    'a1', 0.45, 'b1', 0, ...
    'a2', 0, 'b2', 0, ...
    'a3', 0, 'b3', 0, ...
    'a4', 0, 'b4', 0, ...
    'a5', 0, 'b5', 0 ...
);
cfg.baseParamNumeric = struct( ...
    'r0', 0.012, ...
    'a1', 0.45, 'b1', 0, ...
    'a2', 0, 'b2', 0, ...
    'a3', 0, 'b3', 0, ...
    'a4', 0, 'b4', 0, ...
    'a5', 0, 'b5', 0 ...
);

cfg.candidateRoleCounts = struct( ...
    'strong_positive', 8, ...
    'weak_positive', 4, ...
    'negative', 4 ...
);
cfg.negativeSelectionMode = 'most_negative';
cfg.familyPattern = '^(ep\d+)';

cfg.sampleTarget = 240;
cfg.maxAttempts = 12000;
cfg.randomSeed = 20260415;
cfg.thetaSampleCount = 2048;

cfg.r0Range = [0.007, 0.018];
cfg.AmplitudeRanges = [ ...
    0.20, 0.80; ...
    0.00, 0.40; ...
    0.00, 0.22; ...
    0.00, 0.16; ...
    0.00, 0.10 ...
];

cfg.guardrails = struct( ...
    'maxAmpBudget', 0.92, ...
    'minAmp', 0.22, ...
    'minRadius', 0.003, ...
    'maxRadius', 0.024, ...
    'maxAbsAmpSlope', 1.8 ...
);

cfg.saveModel = false;
cfg.enableBandPlots = false;
cfg.pythonCmd = 'python';
cfg.reuseBaselineByPoint = true;
cfg.positiveGapThresholdHz = 0;
cfg.contactTol = 2e-4;
cfg.contactSampleCount = 1440;
cfg.minExpectedDomains = 2;
cfg.tinyFragmentDomainThreshold = 3;

cfg.resultFieldOrder = { ...
    'sample_id', 'candidate_id', 'shape_id', 'shape_family', 'candidate_role', 'point_id', ...
    'r0', 'a1', 'b1', 'a2', 'b2', 'a3', 'b3', 'a4', 'b4', 'a5', 'b5', ...
    'A1', 'phi1', 'A2', 'phi2', 'A3', 'phi3', 'A4', 'phi4', 'A5', 'phi5', ...
    'sumA', 'deriv_budget', 'min_radius_est', 'max_radius_est', 'max_abs_amp_slope', 'guardrail_pass', ...
    'shift', 'neigs', 'material_case', ...
    'geometry_valid', 'contact_valid', 'contact_length', 'n_domains', 'has_tiny_fragments', ...
    'solve_success', ...
    'gap_target_Hz', 'gap_target_rel', 'gap_lower_band', 'gap_upper_band', 'gap_center_freq', ...
    'gap_lower_edge_Hz', 'gap_upper_edge_Hz', ...
    'ref_gap_Hz', 'ref_gap_rel', 'gap_gain_Hz', 'gap_gain_rel', ...
    'error_message' ...
};

cfg.candidateManifestFieldOrder = { ...
    'candidate_id', 'shape_id', 'shape_file', 'shape_family', 'candidate_role', ...
    'stage1_gap_gain_Hz', 'stage1_gap_target_Hz', 'stage1_candidate_tier', 'family_duplicate' ...
};

cfg.doeFieldOrder = { ...
    'point_id', 'r0', ...
    'A1', 'phi1', 'A2', 'phi2', 'A3', 'phi3', 'A4', 'phi4', 'A5', 'phi5', ...
    'a1', 'b1', 'a2', 'b2', 'a3', 'b3', 'a4', 'b4', 'a5', 'b5', ...
    'sumA', 'deriv_budget', 'min_radius_est', 'max_radius_est', 'max_abs_amp_slope', 'guardrail_pass' ...
};

cfg.configSignature = strjoin({ ...
    cfg.fourierId, ...
    ['material_profile=' cfg.materialProfile], ...
    sprintf('sample_target=%d', cfg.sampleTarget), ...
    sprintf('max_attempts=%d', cfg.maxAttempts), ...
    sprintf('seed=%d', cfg.randomSeed), ...
    sprintf('r0=%.6g:%.6g', cfg.r0Range(1), cfg.r0Range(2)), ...
    sprintf('A1=%.6g:%.6g', cfg.AmplitudeRanges(1,1), cfg.AmplitudeRanges(1,2)), ...
    sprintf('A2=%.6g:%.6g', cfg.AmplitudeRanges(2,1), cfg.AmplitudeRanges(2,2)), ...
    sprintf('A3=%.6g:%.6g', cfg.AmplitudeRanges(3,1), cfg.AmplitudeRanges(3,2)), ...
    sprintf('A4=%.6g:%.6g', cfg.AmplitudeRanges(4,1), cfg.AmplitudeRanges(4,2)), ...
    sprintf('A5=%.6g:%.6g', cfg.AmplitudeRanges(5,1), cfg.AmplitudeRanges(5,2)), ...
    sprintf('budget=%.6g', cfg.guardrails.maxAmpBudget), ...
    sprintf('min_amp=%.6g', cfg.guardrails.minAmp), ...
    sprintf('min_radius=%.6g', cfg.guardrails.minRadius), ...
    sprintf('max_radius=%.6g', cfg.guardrails.maxRadius), ...
    sprintf('max_abs_amp_slope=%.6g', cfg.guardrails.maxAbsAmpSlope), ...
    sprintf('shift=%.6g', cfg.studyShiftHz), ...
    sprintf('neigs=%d', cfg.studyNeigs), ...
    cfg.materialCase ...
}, ';');

ensure_dir(cfg.outDir);
ensure_dir(cfg.tbl1Dir);
ensure_dir(cfg.logsDir);
ensure_dir(cfg.plotDir);
if cfg.saveModel
    ensure_dir(cfg.modelsDir);
end
end

function ensure_dir(pathStr)
if ~exist(pathStr, 'dir')
    mkdir(pathStr);
end
end
