function defs = get_real_ga_summary_fields_v1()
%GET_REAL_GA_SUMMARY_FIELDS_V1 Shared field definitions for optimization summaries.

defs = struct();

defs.planARequiredShapeSummaryColumns = { ...
    'shape_id', ...
    'solve_success_count', ...
    'positive_gap34_gain_rate', ...
    'mean_gap34_gain_Hz', ...
    'best_gap34_gain_Hz' ...
};

defs.planASeedSortFields = { ...
    'mean_gap34_gain_Hz', ...
    'best_gap34_gain_Hz', ...
    'positive_gap34_gain_rate', ...
    'solve_success_count', ...
    'shape_id' ...
};

defs.planASeedSortDirections = { ...
    'descend', ...
    'descend', ...
    'descend', ...
    'descend', ...
    'ascend' ...
};

defs.generationSummaryFields = { ...
    'seed_index', 'seed_shape_id', 'seed_family', 'generation', 'population_size', ...
    'solve_success_count', 'positive_gain_count', 'best_fitness', 'mean_fitness', ...
    'best_sample_id', 'best_gap34_gain_Hz', 'best_gap34_Hz', 'best_distance_from_seed', ...
    'best_a1', 'best_a2', 'best_b2', 'best_a4', 'best_b5', 'best_r0' ...
};

defs.searchSummaryFields = { ...
    'seed_index', 'seed_shape_id', 'seed_family', ...
    'base_sample_id', 'best_sample_id', ...
    'base_fitness', 'best_fitness', 'delta_fitness', ...
    'base_gap34_gain_Hz', 'best_gap34_gain_Hz', 'delta_gap34_gain_Hz', ...
    'best_generation', 'best_individual_index', ...
    'best_a1', 'best_a2', 'best_b2', 'best_a4', 'best_b5', 'best_r0', ...
    'solve_success_count', 'positive_gain_count' ...
};
end
