function cfg = get_stage1_config()
%GET_STAGE1_CONFIG Centralized config for stage-1 shape screening.
% The trusted Fourier mother is fully locked here so higher-order defaults
% from set_params_01.m cannot leak into the stage-1 dataset.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
outDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage1_shape_screening');

cfg = struct();
cfg.rootDir = rootDir;
cfg.shapeDir = fullfile(rootDir, 'data', 'shape_contours');
cfg.outDir = outDir;
cfg.tbl1Dir = fullfile(outDir, 'tbl1_exports');
cfg.modelsDir = fullfile(outDir, 'models');
cfg.logsDir = fullfile(outDir, 'logs');
cfg.resultsMat = fullfile(outDir, 'stage1_screening_results.mat');
cfg.resultsCsv = fullfile(outDir, 'stage1_screening_results.csv');
cfg.summaryByGainCsv = fullfile(outDir, 'stage1_summary_by_gap_gain.csv');
cfg.positiveSummaryCsv = fullfile(outDir, 'stage1_positive_shapes.csv');
cfg.baselineMat = fullfile(outDir, 'baseline_reference.mat');
cfg.baselineCsv = fullfile(outDir, 'baseline_reference.csv');
cfg.plotDir = fullfile(outDir, 'plots');
cfg.bandPlotDir = fullfile(cfg.plotDir, 'band_diagrams');

cfg.fourierId = 'stage1_trusted_baseline_v1';
cfg.materialCase = 'soft_matrix_hard_inclusion';
cfg.studyPName = {'k'};
cfg.studyPListArr = {'range(0,3/(N-1),3)'};
cfg.studyPUnit = {''};
cfg.studySweepType = 'filled';
cfg.studyNeigs = 20;
cfg.studyShiftHz = 200;
cfg.studyShiftExpr = '200[Hz]';

cfg.paramOverrides = struct( ...
    'r0', '0.012[m]', ...
    'a1', 0.45, 'b1', 0, ...
    'a2', 0, 'b2', 0, ...
    'a3', 0, 'b3', 0, ...
    'a4', 0, 'b4', 0, ...
    'a5', 0, 'b5', 0 ...
);
cfg.paramNumeric = struct( ...
    'r0', 0.012, ...
    'a1', 0.45, 'b1', 0, ...
    'a2', 0, 'b2', 0, ...
    'a3', 0, 'b3', 0, ...
    'a4', 0, 'b4', 0, ...
    'a5', 0, 'b5', 0 ...
);

cfg.saveModel = false;
cfg.reuseBaseline = true;
cfg.enableBandPlots = false;
cfg.bandPlotSuccessOnly = true;
cfg.pythonCmd = 'python';
cfg.positiveGapThresholdHz = 0;
cfg.strongPositiveGapGainHz = 5.0;
cfg.weakPositiveGapGainHz = 0.1;
cfg.baselineLikeGapAbsHz = 0.1;
cfg.contactTol = 2e-4;
cfg.contactSampleCount = 1440;
cfg.minExpectedDomains = 2;
cfg.tinyFragmentDomainThreshold = 3;

cfg.resultFieldOrder = { ...
    'sample_id', ...
    'fourier_id', ...
    'shape_id', ...
    'a1', ...
    'a2', ...
    'b1', ...
    'b2', ...
    'a3', ...
    'b3', ...
    'r0', ...
    'shift', ...
    'neigs', ...
    'material_case', ...
    'geometry_valid', ...
    'contact_valid', ...
    'contact_length', ...
    'n_domains', ...
    'has_tiny_fragments', ...
    'solve_success', ...
    'gap_target_Hz', ...
    'gap_target_rel', ...
    'gap_lower_band', ...
    'gap_upper_band', ...
    'gap_center_freq', ...
    'gap_gain_Hz', ...
    'gap_gain_rel', ...
    'is_positive_shape', ...
    'error_message' ...
};

cfg.configSignature = strjoin({ ...
    cfg.fourierId, ...
    sprintf('a1=%.12g', cfg.paramNumeric.a1), ...
    sprintf('a2=%.12g', cfg.paramNumeric.a2), ...
    sprintf('b1=%.12g', cfg.paramNumeric.b1), ...
    sprintf('b2=%.12g', cfg.paramNumeric.b2), ...
    sprintf('a3=%.12g', cfg.paramNumeric.a3), ...
    sprintf('b3=%.12g', cfg.paramNumeric.b3), ...
    sprintf('r0=%.12g', cfg.paramNumeric.r0), ...
    sprintf('shift=%.12g', cfg.studyShiftHz), ...
    sprintf('neigs=%d', cfg.studyNeigs), ...
    cfg.materialCase ...
}, ';');

cfg.baselineShapeId = '__baseline__';
cfg.baselineSampleId = [cfg.fourierId '__baseline'];

ensure_dir(cfg.outDir);
ensure_dir(cfg.tbl1Dir);
ensure_dir(cfg.logsDir);
ensure_dir(cfg.plotDir);
if cfg.saveModel
    ensure_dir(cfg.modelsDir);
end
end

function ensure_dir(pathStr)
if ~exist(pathStr, 'dir')
    mkdir(pathStr);
end
end
