function export_typical_unit_cell_geometry_v1()
% Export a representative COMSOL-built unit-cell geometry with thesis-style layout.

import com.comsol.model.*
import com.comsol.model.util.*

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
addpath(genpath(fullfile(rootDir, 'model_core')));
addpath(genpath(fullfile(rootDir, 'stage2_harmonics')));
addpath(genpath(fullfile(rootDir, 'stage2_harmonics_refine')));
addpath(genpath(fullfile(rootDir, 'stage4_validation')));

sourceCsv = fullfile(rootDir, 'data', 'analysis', 'canonical_local_robustness_v1', 'canonical_local_robustness_merged_v1.csv');
sampleId = 'stage4_validation_targetband_local_robustness_v1_band200_240_ep193_center';
outPath = fullfile(rootDir, 'data', 'analysis', 'thesis_ch3_v1', 'figures', 'figure_3_0_typical_unit_cell.png');

if ~isfile(sourceCsv)
    error('export_typical_unit_cell_geometry_v1:MissingSourceCsv', ...
        'Merged robustness csv not found: %s', sourceCsv);
end

rows = readtable(sourceCsv);
rows = rows(strcmp(string(rows.sample_id), sampleId), :);
if isempty(rows)
    error('export_typical_unit_cell_geometry_v1:MissingSampleRow', ...
        'Sample row not found: %s', sampleId);
end

row = rows(1, :);
shapeId = char(string(pick_text(row, {'shape_id', 'shape_id_x', 'shape_id_y'})));
shapeFile = fullfile(rootDir, 'data', 'shape_contours', [shapeId '.csv']);
if ~isfile(shapeFile)
    error('export_typical_unit_cell_geometry_v1:MissingShapeFile', ...
        'Shape contour not found: %s', shapeFile);
end

cfg = get_stage4_validation_config_targetband_local_robustness_v1();
pointSpec = build_point_spec_from_row(row);

[report, model] = validate_stage2_harmonics_geometry(cfg, pointSpec, shapeFile, sampleId);
if isempty(model) || ~report.geometry_valid
    error('export_typical_unit_cell_geometry_v1:GeometryBuildFailed', ...
        'COMSOL geometry build failed for %s: %s', sampleId, char(string(report.error_message)));
end

export_geometry_figure(model, outPath, shapeFile);

try
    ModelUtil.clear;
catch
end

fprintf('Exported unit-cell geometry: %s\n', outPath);
end

function pointSpec = build_point_spec_from_row(row)
pointSpec = struct( ...
    'main_id', pick_text(row, {'main_id'}), ...
    'point_id', pick_text(row, {'point_id'}), ...
    'a1', pick_numeric(row, {'a1_y', 'a1_x', 'a1'}), ...
    'a2', pick_numeric(row, {'a2_y', 'a2_x', 'a2'}), ...
    'b1', pick_numeric(row, {'b1'}), ...
    'b2', pick_numeric(row, {'b2_y', 'b2_x', 'b2'}), ...
    'r0', pick_numeric(row, {'r0_y', 'r0_x', 'r0'}), ...
    'a3', pick_numeric(row, {'a3'}), ...
    'b3', pick_numeric(row, {'b3'}), ...
    'a4', pick_numeric(row, {'a4'}), ...
    'b4', pick_numeric(row, {'b4'}), ...
    'a5', pick_numeric(row, {'a5'}), ...
    'b5', pick_numeric(row, {'b5'}) ...
);
end

function value = pick_numeric(row, fieldNames)
value = NaN;
for i = 1:numel(fieldNames)
    name = fieldNames{i};
    if ismember(name, row.Properties.VariableNames)
        raw = row.(name)(1);
        if isstring(raw) || ischar(raw)
            num = str2double(string(raw));
        else
            num = double(raw);
        end
        if isfinite(num)
            value = num;
            return;
        end
    end
end
end

function value = pick_text(row, fieldNames)
value = "";
for i = 1:numel(fieldNames)
    name = fieldNames{i};
    if ismember(name, row.Properties.VariableNames)
        value = string(row.(name)(1));
        if strlength(value) > 0
            return;
        end
    end
end
end

function export_geometry_figure(model, outPath, shapeFile)
fig = figure('Visible', 'off', 'Color', 'white', 'Position', [120, 120, 1200, 1350]);
cleanupFig = onCleanup(@() close(fig)); %#ok<NASGU>
ax = axes('Parent', fig, 'Position', [0.10, 0.20, 0.74, 0.73]);
hold(ax, 'on');

xy = readmatrix(shapeFile);
xy = xy(:, 1:2);
xy = xy(~any(isnan(xy), 2), :);
if isempty(xy)
    error('export_geometry_figure:EmptyShapeFile', 'Shape contour is empty: %s', shapeFile);
end
if norm(xy(1, :) - xy(end, :)) > 1e-12
    xy = [xy; xy(1, :)];
end

a = eval_param(model, 'a', 0.05);
halfA = a / 2;

outerX = [-halfA, halfA, halfA, -halfA];
outerY = [-halfA, -halfA, halfA, halfA];
fill(ax, outerX, outerY, [0.84 0.92 0.96], 'EdgeColor', [0.20 0.35 0.45], 'LineWidth', 1.3);
fill(ax, xy(:, 1), xy(:, 2), [1.0 1.0 1.0], 'EdgeColor', [0.20 0.35 0.45], 'LineWidth', 1.4);
plot(ax, xy(:, 1), xy(:, 2), 'Color', [0.20 0.35 0.45], 'LineWidth', 1.4);

axis(ax, 'equal');
axis(ax, 'off');

xl = xlim(ax);
yl = ylim(ax);
padX = 0.18 * diff(xl);
padY = 0.16 * diff(yl);
xlim(ax, [xl(1) - padX, xl(2) + padX]);
ylim(ax, [yl(1) - padY, yl(2) + padY]);

annotation(fig, 'textbox', [0.05, 0.925, 0.90, 0.045], ...
    'String', '图 3-0  典型二维声子晶体单胞几何模型', ...
    'EdgeColor', 'none', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'SimSun', ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'Color', [0.08 0.10 0.12]);
annotation(fig, 'textbox', [0.08, 0.885, 0.84, 0.028], ...
    'String', '基于 COMSOL LiveLink 导出的实际单胞几何，并按论文版式重新排版。', ...
    'EdgeColor', 'none', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'SimSun', ...
    'FontSize', 11.5, ...
    'Color', [0.30 0.36 0.40]);

annotation(fig, 'textarrow', [0.82, 0.76], [0.79, 0.79], ...
    'String', '周期单胞边界', ...
    'FontName', 'SimSun', ...
    'FontSize', 13, ...
    'Color', [0.08 0.08 0.08], ...
    'HeadLength', 7, ...
    'HeadWidth', 7);
annotation(fig, 'textarrow', [0.82, 0.68], [0.66, 0.60], ...
    'String', '连续参数化边界', ...
    'FontName', 'SimSun', ...
    'FontSize', 13, ...
    'Color', [0.08 0.08 0.08], ...
    'HeadLength', 7, ...
    'HeadWidth', 7);
annotation(fig, 'textbox', [0.79, 0.47, 0.18, 0.04], ...
    'String', '基体区域', ...
    'EdgeColor', 'none', ...
    'FontName', 'SimSun', ...
    'FontSize', 13.5);
annotation(fig, 'textbox', [0.79, 0.28, 0.18, 0.04], ...
    'String', '夹杂体区域', ...
    'EdgeColor', 'none', ...
    'FontName', 'SimSun', ...
    'FontSize', 13.5);

annotation(fig, 'rectangle', [0.16, 0.11, 0.034, 0.034], ...
    'FaceColor', [0.84 0.92 0.96], ...
    'EdgeColor', [0.20 0.35 0.45], ...
    'LineWidth', 0.9);
annotation(fig, 'textbox', [0.205, 0.106, 0.28, 0.045], ...
    'String', '材料区域 1（基体）', ...
    'EdgeColor', 'none', ...
    'FontName', 'SimSun', ...
    'FontSize', 13.5, ...
    'VerticalAlignment', 'middle');
annotation(fig, 'rectangle', [0.50, 0.11, 0.034, 0.034], ...
    'FaceColor', [1.0 1.0 1.0], ...
    'EdgeColor', [0.20 0.35 0.45], ...
    'LineWidth', 0.9);
annotation(fig, 'textbox', [0.545, 0.106, 0.30, 0.045], ...
    'String', '材料区域 2（夹杂体）', ...
    'EdgeColor', 'none', ...
    'FontName', 'SimSun', ...
    'FontSize', 13.5, ...
    'VerticalAlignment', 'middle');
annotation(fig, 'textbox', [0.12, 0.045, 0.72, 0.03], ...
    'String', '注：该图由 COMSOL 几何模型导出后重新整理，重点展示单胞边界、材料分区与局部结构特征。', ...
    'EdgeColor', 'none', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'SimSun', ...
    'FontSize', 12.5, ...
    'Color', [0.15 0.15 0.15]);

outDir = fileparts(outPath);
if ~exist(outDir, 'dir')
    mkdir(outDir);
end
exportgraphics(fig, outPath, 'Resolution', 300);
end

function value = eval_param(model, expr, fallback)
value = fallback;
try
    value = model.param.evaluate(expr);
    if ischar(value) || isstring(value)
        value = str2double(value);
    end
catch
end
if ~isfinite(value)
    value = fallback;
end

end
