function profile = get_material_profile(profileName)
%GET_MATERIAL_PROFILE Return one registered material profile definition.

if nargin < 1 || isempty(profileName)
    profileName = resolve_material_profile_name('baseline_soft_hard');
end

profileName = char(string(profileName));
switch profileName
    case 'baseline_soft_hard'
        profile = make_profile( ...
            'baseline_soft_hard', ...
            'Default soft-matrix / hard-inclusion profile used by the current mainline.', ...
            make_phase('mat3', 'soft_matrix', '1050', '3e5', '0.49'), ...
            make_phase('mat4', 'hard_inclusion', '7850', '2.1e10', '0.3') ...
        );
    case 'alt_soft_hard_1'
        profile = make_profile( ...
            'alt_soft_hard_1', ...
            'Alternative profile with a slightly stiffer soft matrix and a moderately softer inclusion.', ...
            make_phase('mat3', 'soft_matrix', '1120', '5e5', '0.47'), ...
            make_phase('mat4', 'hard_inclusion', '7600', '1.5e10', '0.29') ...
        );
    case 'alt_soft_hard_2'
        profile = make_profile( ...
            'alt_soft_hard_2', ...
            'Alternative profile with a softer matrix and a denser, stiffer inclusion.', ...
            make_phase('mat3', 'soft_matrix', '980', '2e5', '0.495'), ...
            make_phase('mat4', 'hard_inclusion', '8900', '3.0e10', '0.33') ...
        );
    otherwise
        error('get_material_profile:UnknownProfile', ...
            'Unknown material profile "%s". Supported profiles: baseline_soft_hard, alt_soft_hard_1, alt_soft_hard_2.', ...
            profileName);
end
end

function profile = make_profile(name, description, matrixPhase, inclusionPhase)
profile = struct( ...
    'name', name, ...
    'material_case', 'soft_matrix_hard_inclusion', ...
    'description', description, ...
    'matrix', matrixPhase, ...
    'inclusion', inclusionPhase ...
);
end

function phase = make_phase(tag, role, density, youngsModulus, poissonsRatio)
phase = struct( ...
    'tag', tag, ...
    'role', role, ...
    'density', char(string(density)), ...
    'youngsmodulus', char(string(youngsModulus)), ...
    'poissonsratio', char(string(poissonsRatio)) ...
);
end
