function cfg = get_stage4_validation_config_canonical_targetband_refinement_v1()
%GET_STAGE4_VALIDATION_CONFIG_CANONICAL_TARGETBAND_REFINEMENT_V1
% Config for canonical target-band local refinement validation runs.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
validationDir = fullfile(rootDir, 'data', 'ml_runs', 'canonical_targetband_refinement_v1', 'validation_manifest_v1');
outDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage4_validation_canonical_targetband_refinement_v1');
cfg = build_stage4_validation_config( ...
    'stage4_validation_canonical_targetband_refinement_v1', ...
    validationDir, ...
    'canonical_targetband_refinement_validation_manifest_v1.csv', ...
    'canonical_targetband_refinement_validation_manifest_summary_v1.json', ...
    outDir);
end
