function cfg = get_stage4_validation_config_cahfp_v1()
%GET_STAGE4_VALIDATION_CONFIG_CAHFP_V1
% Contact-aware high-frequency pilot validation.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
validationDir = fullfile(rootDir, 'data', 'ml_runs', 'contactaware_highfreq_pilot_v1', 'validation_manifest_v1');
outDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage4_validation_contactaware_highfreq_pilot_v1');
cfg = build_stage4_validation_config( ...
    'stage4_validation_contactaware_highfreq_pilot_v1', ...
    validationDir, ...
    'contactaware_highfreq_manifest_v1.csv', ...
    'contactaware_highfreq_manifest_summary_v1.json', ...
    outDir);
cfg.shapeDir = fullfile(rootDir, 'data', 'contactaware_highfreq_pilot_v1', 'shape_contours');
end
