function cfg = get_stage4_validation_config_hbmp_round2_v1()
%GET_STAGE4_VALIDATION_CONFIG_HBMP_ROUND2_V1
% Short-name entry for high-band parameter migration round-2 validation.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
validationDir = fullfile(rootDir, 'data', 'ml_runs', 'highband_param_migration_round2_v1', 'validation_manifest_v1');
outDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage4_validation_highband_param_migration_round2_v1');
cfg = build_stage4_validation_config( ...
    'stage4_validation_highband_param_migration_round2_v1', ...
    validationDir, ...
    'highband_param_migration_round2_manifest_v1.csv', ...
    'highband_param_migration_round2_manifest_summary_v1.json', ...
    outDir);
cfg.shapeDir = fullfile(rootDir, 'data', 'highband_param_migration_round2_v1', 'shape_contours');
end
