function cfg = get_stage4_validation_config_mbp_top1_v11_freeze()
%GET_STAGE4_VALIDATION_CONFIG_MBP_TOP1_V11_FREEZE
% Short-name config for six-band v11 freeze predictor top-1 COMSOL validation.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
validationDir = fullfile(rootDir, 'data', 'ml_runs', ...
    'targetband_multiband_predictor_top1_v11_12gen_freeze_v1', 'validation_manifest_v1');
outDir = fullfile(rootDir, 'data', 'comsol_batch', ...
    'stage4_validation_multiband_predictor_top1_v11_12gen_freeze_v1');
cfg = build_stage4_validation_config( ...
    'stage4_validation_multiband_predictor_top1_v11_12gen_freeze_v1', ...
    validationDir, ...
    'targetband_multiband_predictor_top1_v11_12gen_freeze_manifest_v1.csv', ...
    'targetband_multiband_predictor_top1_v11_12gen_freeze_manifest_summary_v1.json', ...
    outDir);
end
