function cfg = get_stage4_validation_config_targetband_family_expansion_probe_v1()
%GET_STAGE4_VALIDATION_CONFIG_TARGETBAND_FAMILY_EXPANSION_PROBE_V1
% Config for the first-batch weak-band family expansion probe.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
validationDir = fullfile(rootDir, 'data', 'ml_runs', 'targetband_family_expansion_probe_v1', 'validation_manifest_v1');
outDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage4_validation_targetband_family_expansion_probe_v1');
cfg = build_stage4_validation_config( ...
    'stage4_validation_targetband_family_expansion_probe_v1', ...
    validationDir, ...
    'targetband_family_expansion_probe_manifest_v1.csv', ...
    'targetband_family_expansion_probe_manifest_summary_v1.json', ...
    outDir);
end
