function cfg = get_stage4_validation_config_tbf_probe_round3_v1()
%GET_STAGE4_VALIDATION_CONFIG_TBF_PROBE_ROUND3_V1
% Short-name config for family expansion probe round 3.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
validationDir = fullfile(rootDir, 'data', 'ml_runs', 'targetband_family_expansion_probe_round3_v1', 'validation_manifest_v1');
outDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage4_validation_targetband_family_expansion_probe_round3_v1');
cfg = build_stage4_validation_config( ...
    'stage4_validation_targetband_family_expansion_probe_round3_v1', ...
    validationDir, ...
    'targetband_family_expansion_probe_round3_manifest_v1.csv', ...
    'targetband_family_expansion_probe_round3_manifest_summary_v1.json', ...
    outDir);
end
