function cfg = get_stage4_validation_config_tb180_predictor_top6_v11_freeze()
%GET_STAGE4_VALIDATION_CONFIG_TB180_PREDICTOR_TOP6_V11_FREEZE
% Short-name config for 180-220 Hz v11 freeze predictor Top-6 COMSOL validation.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
validationDir = fullfile(rootDir, 'data', 'ml_runs', ...
    'targetband180_220_predictor_top6_v11_12gen_freeze_v1', 'validation_manifest_v1');
outDir = fullfile(rootDir, 'data', 'comsol_batch', ...
    'stage4_validation_targetband180_220_predictor_top6_v11_12gen_freeze_v1');
cfg = build_stage4_validation_config( ...
    'stage4_validation_targetband180_220_predictor_top6_v11_12gen_freeze_v1', ...
    validationDir, ...
    'targetband180_220_predictor_top6_v11_12gen_freeze_manifest_v1.csv', ...
    'targetband180_220_predictor_top6_v11_12gen_freeze_manifest_summary_v1.json', ...
    outDir);
end
