function cfg = get_stage4_validation_config_multiband_predictor_top1_v1()
%GET_STAGE4_VALIDATION_CONFIG_MULTIBAND_PREDICTOR_TOP1_V1
% Config for six-band predictor top-1 COMSOL validation.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
validationDir = fullfile(rootDir, 'data', 'ml_runs', ...
    'targetband_multiband_predictor_top1_v1', 'validation_manifest_v1');
outDir = fullfile(rootDir, 'data', 'comsol_batch', ...
    'stage4_validation_multiband_predictor_top1_v1');
cfg = build_stage4_validation_config( ...
    'stage4_validation_multiband_predictor_top1_v1', ...
    validationDir, ...
    'targetband_multiband_predictor_top1_manifest_v1.csv', ...
    'targetband_multiband_predictor_top1_manifest_summary_v1.json', ...
    outDir);
end
