function cfg = get_stage4_validation_config_ctb_direct_scan_round2_v1()
%GET_STAGE4_VALIDATION_CONFIG_CTB_DIRECT_SCAN_ROUND2_V1
% Config for the second-round focused direct local scan around the current best ep253 point.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
validationDir = fullfile(rootDir, 'data', 'ml_runs', 'canonical_targetband_direct_scan_round2_v1', 'validation_manifest_v1');
outDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage4_validation_canonical_targetband_direct_scan_round2_v1');
cfg = build_stage4_validation_config( ...
    'stage4_validation_canonical_targetband_direct_scan_round2_v1', ...
    validationDir, ...
    'canonical_targetband_direct_scan_round2_manifest_v1.csv', ...
    'canonical_targetband_direct_scan_round2_manifest_summary_v1.json', ...
    outDir);
end
