function cfg = get_stage4_validation_config_targetband_local_robustness_v1()
%GET_STAGE4_VALIDATION_CONFIG_TARGETBAND_LOCAL_ROBUSTNESS_V1 Config for canonical local-neighborhood robustness validation.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
validationDir = fullfile(rootDir, 'data', 'ml_runs', 'canonical_inverse_design_local_robustness_v1', 'validation_manifest_v1');
outDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage4_validation_targetband_local_robustness_v1');
cfg = build_stage4_validation_config( ...
    'stage4_validation_targetband_local_robustness_v1', ...
    validationDir, ...
    'canonical_local_robustness_manifest_v1.csv', ...
    'canonical_local_robustness_manifest_summary_v1.json', ...
    outDir);
end
