function cfg = get_stage4_validation_config_satbp_v1()
%GET_STAGE4_VALIDATION_CONFIG_SATBP_V1
% Short-name entry for shape archetype target-band pilot validation.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
validationDir = fullfile(rootDir, 'data', 'ml_runs', 'shape_archetype_targetband_pilot_v1', 'validation_manifest_v1');
outDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage4_validation_shape_archetype_targetband_pilot_v1');
cfg = build_stage4_validation_config( ...
    'stage4_validation_shape_archetype_targetband_pilot_v1', ...
    validationDir, ...
    'shape_archetype_targetband_pilot_manifest_v1.csv', ...
    'shape_archetype_targetband_pilot_manifest_summary_v1.json', ...
    outDir);
end
