function doeTable = get_stage2_harmonics_doe_points(cfg)
%GET_STAGE2_HARMONICS_DOE_POINTS Build the focused high-order harmonic DOE.
% Each principal main point gets a center case plus one-factor perturbations
% on a3/b3/a4/b4/a5/b5.

rows = struct([]);
for i = 1:numel(cfg.mainPointSpecs)
    main = cfg.mainPointSpecs(i);
    base = struct( ...
        'main_id', string(main.main_id), ...
        'a1', main.a1, ...
        'a2', main.a2, ...
        'b2', main.b2, ...
        'r0', main.r0, ...
        'a3', 0, 'b3', 0, 'a4', 0, 'b4', 0, 'a5', 0, 'b5', 0 ...
    );

    rows = append_row(rows, build_row(base, 'h00_center')); %#ok<AGROW>
    rows = append_row(rows, build_row(setfield(base, 'a3', cfg.a3Values(1)), 'h01_a3_lo')); %#ok<SFLD,AGROW>
    rows = append_row(rows, build_row(setfield(base, 'a3', cfg.a3Values(2)), 'h02_a3_hi')); %#ok<SFLD,AGROW>
    rows = append_row(rows, build_row(setfield(base, 'b3', cfg.b3Values(1)), 'h03_b3_lo')); %#ok<SFLD,AGROW>
    rows = append_row(rows, build_row(setfield(base, 'b3', cfg.b3Values(2)), 'h04_b3_hi')); %#ok<SFLD,AGROW>
    rows = append_row(rows, build_row(setfield(base, 'a4', cfg.a4Values(1)), 'h05_a4_lo')); %#ok<SFLD,AGROW>
    rows = append_row(rows, build_row(setfield(base, 'a4', cfg.a4Values(2)), 'h06_a4_hi')); %#ok<SFLD,AGROW>
    rows = append_row(rows, build_row(setfield(base, 'b4', cfg.b4Values(1)), 'h07_b4_lo')); %#ok<SFLD,AGROW>
    rows = append_row(rows, build_row(setfield(base, 'b4', cfg.b4Values(2)), 'h08_b4_hi')); %#ok<SFLD,AGROW>
    rows = append_row(rows, build_row(setfield(base, 'a5', cfg.a5Values(1)), 'h09_a5_lo')); %#ok<SFLD,AGROW>
    rows = append_row(rows, build_row(setfield(base, 'a5', cfg.a5Values(2)), 'h10_a5_hi')); %#ok<SFLD,AGROW>
    rows = append_row(rows, build_row(setfield(base, 'b5', cfg.b5Values(1)), 'h11_b5_lo')); %#ok<SFLD,AGROW>
    rows = append_row(rows, build_row(setfield(base, 'b5', cfg.b5Values(2)), 'h12_b5_hi')); %#ok<SFLD,AGROW>
end

doeTable = struct2table(rows, 'AsArray', true);
doeTable = doeTable(:, cfg.doeFieldOrder);
writetable(doeTable, cfg.doeManifestCsv);
end

function row = build_row(base, suffix)
row = struct( ...
    'main_id', string(base.main_id), ...
    'point_id', string(sprintf('%s_%s', char(string(base.main_id)), suffix)), ...
    'a1', base.a1, ...
    'a2', base.a2, ...
    'b2', base.b2, ...
    'r0', base.r0, ...
    'a3', base.a3, ...
    'b3', base.b3, ...
    'a4', base.a4, ...
    'b4', base.b4, ...
    'a5', base.a5, ...
    'b5', base.b5 ...
);
end

function rows = append_row(rows, row)
if isempty(rows)
    rows = row;
else
    rows(end + 1) = row;
end
end
