function cfg = get_stage2_harmonics_config()
%GET_STAGE2_HARMONICS_CONFIG Focused high-order harmonic screening config.
% This stage fixes a small set of robust shapes and principal Fourier points,
% then probes a3/b3/a4/b4/a5/b5 with one-factor-at-a-time perturbations.

thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
outDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage2_harmonics');
refineDir = fullfile(rootDir, 'data', 'comsol_batch', 'stage2_refine');

cfg = struct();
cfg.rootDir = rootDir;
cfg.refineDir = refineDir;
cfg.shapeDir = fullfile(rootDir, 'data', 'shape_contours');
cfg.outDir = outDir;
cfg.tbl1Dir = fullfile(outDir, 'tbl1_exports');
cfg.modelsDir = fullfile(outDir, 'models');
cfg.logsDir = fullfile(outDir, 'logs');
cfg.plotDir = fullfile(outDir, 'plots');
cfg.bandPlotDir = fullfile(cfg.plotDir, 'band_diagrams');

cfg.refineShapeSummaryCsv = fullfile(refineDir, 'stage2_refine_shape_summary.csv');
cfg.refineCandidateManifestCsv = fullfile(refineDir, 'stage2_refine_candidate_manifest.csv');
cfg.candidateManifestCsv = fullfile(outDir, 'stage2_harmonics_candidate_manifest.csv');
cfg.doeManifestCsv = fullfile(outDir, 'stage2_harmonics_doe_manifest.csv');
cfg.baselineByPointMat = fullfile(outDir, 'baseline_by_point.mat');
cfg.baselineByPointCsv = fullfile(outDir, 'baseline_by_point.csv');
cfg.resultsMat = fullfile(outDir, 'stage2_harmonics_results.mat');
cfg.resultsCsv = fullfile(outDir, 'stage2_harmonics_results.csv');
cfg.shapeSummaryCsv = fullfile(outDir, 'stage2_harmonics_shape_summary.csv');
cfg.pointSummaryCsv = fullfile(outDir, 'stage2_harmonics_point_summary.csv');

cfg.fourierId = 'stage2_harmonics_v1';
cfg.materialCase = 'soft_matrix_hard_inclusion';
cfg.studyPName = {'k'};
cfg.studyPListArr = {'range(0,3/(N-1),3)'};
cfg.studyPUnit = {''};
cfg.studySweepType = 'filled';
cfg.studyNeigs = 20;
cfg.studyShiftHz = 200;
cfg.studyShiftExpr = '200[Hz]';

cfg.baseParamOverrides = struct( ...
    'r0', '0.012[m]', ...
    'a1', 0.45, 'b1', 0, ...
    'a2', 0, 'b2', 0, ...
    'a3', 0, 'b3', 0, ...
    'a4', 0, 'b4', 0, ...
    'a5', 0, 'b5', 0 ...
);
cfg.baseParamNumeric = struct( ...
    'r0', 0.012, ...
    'a1', 0.45, 'b1', 0, ...
    'a2', 0, 'b2', 0, ...
    'a3', 0, 'b3', 0, ...
    'a4', 0, 'b4', 0, ...
    'a5', 0, 'b5', 0 ...
);

cfg.harmonicCandidateCount = 4;
cfg.minPositiveGainRatio = 0.95;
cfg.minMeanGapGainHz = 11.0;
cfg.minSolvedPoints = 21;
cfg.familyPattern = '^(ep\d+)';
cfg.mainPointSpecs = [ ...
    struct('main_id', 'rf05', 'a1', 0.45, 'a2', -0.12, 'b2', 0.04, 'r0', 0.0120); ...
    struct('main_id', 'rf19', 'a1', 0.50, 'a2', -0.12, 'b2', 0.00, 'r0', 0.0120); ...
    struct('main_id', 'rf09', 'a1', 0.50, 'a2', -0.12, 'b2', 0.04, 'r0', 0.0120); ...
    struct('main_id', 'rf02', 'a1', 0.40, 'a2', -0.08, 'b2', 0.04, 'r0', 0.0120) ...
];
cfg.harmonicDoeVersion = 'oat_harmonics_v1';

cfg.a3Values = [-0.04, 0.04];
cfg.b3Values = [-0.04, 0.04];
cfg.a4Values = [-0.03, 0.03];
cfg.b4Values = [-0.03, 0.03];
cfg.a5Values = [-0.02, 0.02];
cfg.b5Values = [-0.02, 0.02];

cfg.saveModel = false;
cfg.enableBandPlots = false;
cfg.pythonCmd = 'python';
cfg.reuseBaselineByPoint = true;
cfg.positiveGapThresholdHz = 0;
cfg.contactTol = 2e-4;
cfg.contactSampleCount = 1440;
cfg.minExpectedDomains = 2;
cfg.tinyFragmentDomainThreshold = 3;

cfg.resultFieldOrder = { ...
    'sample_id', ...
    'candidate_id', ...
    'shape_id', ...
    'shape_family', ...
    'candidate_role', ...
    'main_id', ...
    'point_id', ...
    'a1', ...
    'a2', ...
    'b2', ...
    'r0', ...
    'a3', ...
    'b3', ...
    'a4', ...
    'b4', ...
    'a5', ...
    'b5', ...
    'shift', ...
    'neigs', ...
    'material_case', ...
    'geometry_valid', ...
    'contact_valid', ...
    'contact_length', ...
    'n_domains', ...
    'has_tiny_fragments', ...
    'solve_success', ...
    'gap_target_Hz', ...
    'gap_target_rel', ...
    'gap_lower_band', ...
    'gap_upper_band', ...
    'gap_center_freq', ...
    'ref_gap_Hz', ...
    'ref_gap_rel', ...
    'gap_gain_Hz', ...
    'gap_gain_rel', ...
    'error_message' ...
};

cfg.candidateManifestFieldOrder = { ...
    'candidate_id', ...
    'shape_id', ...
    'shape_file', ...
    'shape_family', ...
    'candidate_role', ...
    'source_refine_candidate_id', ...
    'source_positive_gain_ratio', ...
    'source_mean_gap_gain_Hz', ...
    'source_best_gap_gain_Hz' ...
};

cfg.doeFieldOrder = {'main_id', 'point_id', 'a1', 'a2', 'b2', 'r0', 'a3', 'b3', 'a4', 'b4', 'a5', 'b5'};

signatureParts = [{ ...
    cfg.fourierId, ...
    sprintf('cand=%d', cfg.harmonicCandidateCount), ...
    sprintf('minratio=%.12g', cfg.minPositiveGainRatio), ...
    sprintf('minmean=%.12g', cfg.minMeanGapGainHz), ...
    sprintf('minsolved=%d', cfg.minSolvedPoints), ...
    cfg.harmonicDoeVersion, ...
    sprintf('mains=%d', numel(cfg.mainPointSpecs)), ...
    sprintf('shift=%.12g', cfg.studyShiftHz), ...
    sprintf('neigs=%d', cfg.studyNeigs), ...
    cfg.materialCase ...
}, build_main_point_signature_parts(cfg.mainPointSpecs), { ...
    vector_signature('a3', cfg.a3Values), ...
    vector_signature('b3', cfg.b3Values), ...
    vector_signature('a4', cfg.a4Values), ...
    vector_signature('b4', cfg.b4Values), ...
    vector_signature('a5', cfg.a5Values), ...
    vector_signature('b5', cfg.b5Values), ...
    sprintf('contact_tol=%.12g', cfg.contactTol), ...
    sprintf('contact_samples=%d', cfg.contactSampleCount) ...
}];
cfg.configSignature = strjoin(signatureParts, ';');

ensure_dir(cfg.outDir);
ensure_dir(cfg.tbl1Dir);
ensure_dir(cfg.logsDir);
ensure_dir(cfg.plotDir);
if cfg.saveModel
    ensure_dir(cfg.modelsDir);
end
end

function ensure_dir(pathStr)
if ~exist(pathStr, 'dir')
    mkdir(pathStr);
end
end

function parts = build_main_point_signature_parts(mainPointSpecs)
parts = cell(1, numel(mainPointSpecs));
for i = 1:numel(mainPointSpecs)
    spec = mainPointSpecs(i);
    parts{i} = sprintf('main=%s,%.12g,%.12g,%.12g,%.12g', ...
        char(string(spec.main_id)), spec.a1, spec.a2, spec.b2, spec.r0);
end
end

function part = vector_signature(name, values)
valueText = strjoin(arrayfun(@(v) sprintf('%.12g', v), values, 'UniformOutput', false), ',');
part = sprintf('%s=%s', name, valueText);
end
