function cfg = get_comsol_in_loop_ga_optimization_refine_config_v1()
%GET_COMSOL_IN_LOOP_GA_OPTIMIZATION_REFINE_CONFIG_V1
% Real refinement on survivor basins selected from the optimization probe stage.

cfg = get_comsol_in_loop_ga_optimization_probe_config_v1();
cfg.gaId = 'comsol_in_loop_ga_optimization_refine_v1';
cfg = apply_real_ga_output_layout_v1(cfg, fullfile(cfg.rootDir, 'data', 'comsol_batch', cfg.gaId));

cfg.probeGaId = 'comsol_in_loop_ga_optimization_probe_v1';
cfg.probeOutDir = fullfile(cfg.rootDir, 'data', 'comsol_batch', cfg.probeGaId);
cfg.probeShapeSummaryCsv = fullfile(cfg.probeOutDir, 'comsol_in_loop_ga_shape_summary.csv');
cfg.probeSearchSummaryCsv = fullfile(cfg.probeOutDir, 'ga_search_summary_v1.csv');
cfg.probeBestCandidatesCsv = fullfile(cfg.probeOutDir, 'ga_best_candidates_v1.csv');
cfg.probeTopKSeeds = 5;
cfg.probeMinMeanGainHz = 0.0;
cfg.probeMinPositiveRate = 0.0;
cfg.probeMinSolveSuccessCount = 1;

cfg.forceSeedShapeIds = cellstr(select_optimization_probe_seed_ids_v1( ...
    cfg.probeShapeSummaryCsv, ...
    cfg.probeTopKSeeds, ...
    cfg.probeMinMeanGainHz, ...
    cfg.probeMinPositiveRate, ...
    cfg.probeMinSolveSuccessCount));
cfg.topKSeeds = numel(cfg.forceSeedShapeIds);
ensure_dir(cfg.outDir);
ensure_dir(cfg.tbl1Dir);
ensure_dir(cfg.logsDir);
ensure_dir(cfg.plotDir);
if cfg.saveModel
    ensure_dir(cfg.modelsDir);
end
cfg.refineSeedScoredCsv = fullfile(cfg.outDir, 'ga_refine_seed_selection_v1.csv');
cfg.seedScoredCsv = build_optimization_refine_seed_csv_v1( ...
    cfg.seedScoredCsv, ...
    cfg.probeBestCandidatesCsv, ...
    string(cfg.forceSeedShapeIds(:)), ...
    cfg.refineSeedScoredCsv);

cfg.populationSize = 12;
cfg.generations = 6;
cfg.eliteCount = 2;
cfg.mutationRate = 0.22;
cfg.mutationScale = 0.09;
cfg.topCandidatesPerSeedExport = 3;

cfg.localHalfWidths = struct( ...
    'a1', 0.0060, ...
    'a2', 0.0120, ...
    'b1', 0.0100, ...
    'b2', 0.0100, ...
    'a3', 0.0080, ...
    'b3', 0.0080, ...
    'a4', 0.0070, ...
    'b4', 0.0070, ...
    'a5', 0.0050, ...
    'b5', 0.0050, ...
    'r0', 0.00040 ...
);

signatureParts = [ ...
    get_real_ga_base_signature_parts_v1(cfg), ...
    { ...
    'optimization_mode=refine', ...
    ['probe_shape_summary=' file_signature_v1(cfg.probeShapeSummaryCsv)], ...
    ['probe_search_summary=' file_signature_v1(cfg.probeSearchSummaryCsv)], ...
    ['probe_best_candidates=' file_signature_v1(cfg.probeBestCandidatesCsv)], ...
    ['refine_seed_scored_csv=' file_signature_v1(cfg.refineSeedScoredCsv)], ...
    ['probe_top_k=' num2str(cfg.probeTopKSeeds)], ...
    ['probe_min_mean=' num2str(cfg.probeMinMeanGainHz, '%.12g')], ...
    ['probe_min_rate=' num2str(cfg.probeMinPositiveRate, '%.12g')], ...
    ['probe_min_solve=' num2str(cfg.probeMinSolveSuccessCount)] ...
    } ...
];
cfg.configSignature = join_signature_parts_v1(signatureParts);
end

function ensure_dir(pathStr)
if ~exist(pathStr, 'dir')
    mkdir(pathStr);
end
end
