function cfg = get_comsol_in_loop_ga_global_config_v1()
%GET_COMSOL_IN_LOOP_GA_GLOBAL_CONFIG_V1 Config for the true global COMSOL-in-loop GA baseline.

cfg = get_comsol_in_loop_ga_config_v1();
cfg.gaId = 'comsol_in_loop_true_global_ga_v1';

% The true global baseline uses one unified population over shape + parameter genes.
cfg.activeParamNames = {'a1','b1','a2','b2','r0','a3','b3','a4','b4','a5','b5'};
cfg.populationSize = 40;
cfg.maxGenerations = 25;
cfg.eliteCount = 4;
cfg.shapeMutationRate = 0.20;
cfg.continuousMutationRate = 0.25;
cfg.continuousMutationScale = 0.10;

cfg.globalBounds.b1 = [-0.05, 0.05];
cfg.globalBounds.a3 = [-0.04, 0.04];
cfg.globalBounds.b3 = [-0.04, 0.04];
cfg.globalBounds.a4 = [-0.03, 0.03];
cfg.globalBounds.b4 = [-0.03, 0.03];
cfg.globalBounds.a5 = [-0.02, 0.02];
cfg.globalBounds.b5 = [-0.02, 0.02];

cfg.referenceMainId = 'rf09';
cfg.referencePointId = 'rf09_h00_center';
cfg.referencePointSpec = struct( ...
    'main_id', 'rf09', ...
    'point_id', 'rf09_h00_center', ...
    'a1', 0.50, ...
    'a2', -0.12, ...
    'b1', 0.0, ...
    'b2', 0.04, ...
    'r0', 0.0120, ...
    'a3', 0.0, ...
    'b3', 0.0, ...
    'a4', 0.0, ...
    'b4', 0.0, ...
    'a5', 0.0, ...
    'b5', 0.0 ...
);

cfg.shapePoolMode = 'stage1_screened';
cfg.shapePoolCsv = fullfile(cfg.rootDir, 'data', 'comsol_batch', 'stage1_shape_screening', 'stage1_summary_by_gap_gain.csv');
cfg.shapePoolRequireGeometryValid = true;
cfg.shapePoolRequireContactValid = true;
cfg.shapePoolRequireSolveSuccess = true;
cfg.shapePoolIncludeTiers = {'strong_positive', 'weak_positive', 'neutral_or_baseline_like', 'negative'};
cfg.topCandidatesExport = 20;

cfg.enableEarlyStop = true;
cfg.earlyStopPatience = 4;
cfg.earlyStopMinDeltaFitness = 0.2;
cfg.earlyStopMinGenerations = 6;

% Cooperative mode lets multiple full MATLAB+COMSOL sessions share one GA run.
cfg.cooperativeMode = false;
cfg.cooperativeWorkerId = '';
cfg.cooperativePollSeconds = 5;
cfg.cooperativeLockTimeoutSeconds = 300;
cfg.cooperativeLockStaleSeconds = 1800;
cfg.cooperativeClaimTimeoutSeconds = 21600;

cfg = apply_real_ga_output_layout_v1(cfg, fullfile(cfg.rootDir, 'data', 'comsol_batch', cfg.gaId));
cfg.shapePoolResolvedCsv = fullfile(cfg.outDir, 'ga_shape_pool_v1.csv');
cfg.pointManifestCsv = fullfile(cfg.outDir, 'ga_point_manifest_v1.csv');
cfg.cooperativeStateLock = fullfile(cfg.outDir, 'ga_state_v1.lock');

signatureParts = [ ...
    get_real_ga_base_signature_parts_v1(cfg), ...
    { ...
    ['global_mode=true'], ...
    ['shape_pool_mode=' cfg.shapePoolMode], ...
    ['shape_pool_csv=' file_signature_v1(cfg.shapePoolCsv)], ...
    ['shape_pool_tiers=' strjoin(string(cfg.shapePoolIncludeTiers), ',')], ...
    ['shape_pool_require_geometry=' num2str(cfg.shapePoolRequireGeometryValid)], ...
    ['shape_pool_require_contact=' num2str(cfg.shapePoolRequireContactValid)], ...
    ['shape_pool_require_solve=' num2str(cfg.shapePoolRequireSolveSuccess)], ...
    ['population=' num2str(cfg.populationSize)], ...
    ['max_generations=' num2str(cfg.maxGenerations)], ...
    ['shape_mutation=' num2str(cfg.shapeMutationRate, '%.12g')], ...
    ['early_stop=' num2str(cfg.enableEarlyStop)], ...
    ['early_stop_patience=' num2str(cfg.earlyStopPatience)], ...
    ['early_stop_delta=' num2str(cfg.earlyStopMinDeltaFitness, '%.12g')], ...
    ['early_stop_min_generations=' num2str(cfg.earlyStopMinGenerations)], ...
    ['reference_point=' cfg.referencePointId] ...
    } ...
];
cfg.configSignature = join_signature_parts_v1(signatureParts);

ensure_dir(cfg.outDir);
ensure_dir(cfg.tbl1Dir);
ensure_dir(cfg.logsDir);
ensure_dir(cfg.plotDir);
if cfg.saveModel
    ensure_dir(cfg.modelsDir);
end
end

function ensure_dir(pathStr)
if ~exist(pathStr, 'dir')
    mkdir(pathStr);
end
end
