function cfg = get_comsol_in_loop_ga_plan_a_bridge_config_v1()
%GET_COMSOL_IN_LOOP_GA_PLAN_A_BRIDGE_CONFIG_V1
% Build the real-GA config by using plan-A real validation as the seed gate.

cfg = get_comsol_in_loop_ga_config_v1();
gate = get_plan_a_seed_gate_defaults_v1();

cfg.gaId = 'comsol_in_loop_ga_plan_a_bridge_v1';
cfg.planAWorktreeDir = fullfile(cfg.rootDir, '.worktrees', 'optimization-plan-a');
cfg.planAValidationShapeSummaryCsv = fullfile( ...
    cfg.planAWorktreeDir, ...
    'data', 'comsol_batch', 'stage4_validation_ab_ga_plan_a_expanded_v1', ...
    'stage4_validation_shape_summary.csv');
cfg.planATopKSeeds = gate.topKSeeds;
cfg.planAMinMeanGainHz = gate.minMeanGainHz;
cfg.planAMinPositiveRate = gate.minPositiveRate;
cfg.planAMinSolveSuccessCount = gate.minSolveSuccessCount;

cfg.forceSeedShapeIds = cellstr(select_plan_a_validated_seed_ids_v1( ...
    cfg.planAValidationShapeSummaryCsv, ...
    cfg.planATopKSeeds, ...
    cfg.planAMinMeanGainHz, ...
    cfg.planAMinPositiveRate, ...
    cfg.planAMinSolveSuccessCount));
cfg.topKSeeds = numel(cfg.forceSeedShapeIds);

cfg = apply_real_ga_output_layout_v1(cfg, fullfile(cfg.rootDir, 'data', 'comsol_batch', cfg.gaId));

signatureParts = [ ...
    get_real_ga_base_signature_parts_v1(cfg), ...
    { ...
    ['plan_a_shape_summary=' file_signature_v1(cfg.planAValidationShapeSummaryCsv)], ...
    ['plan_a_min_mean=' num2str(cfg.planAMinMeanGainHz, '%.12g')], ...
    ['plan_a_min_rate=' num2str(cfg.planAMinPositiveRate, '%.12g')], ...
    ['plan_a_min_solve=' num2str(cfg.planAMinSolveSuccessCount)], ...
    ['plan_a_top_k=' num2str(cfg.planATopKSeeds)] ...
    } ...
];
cfg.configSignature = join_signature_parts_v1(signatureParts);

ensure_dir(cfg.outDir);
ensure_dir(cfg.tbl1Dir);
ensure_dir(cfg.logsDir);
ensure_dir(cfg.plotDir);
if cfg.saveModel
    ensure_dir(cfg.modelsDir);
end
end

function ensure_dir(pathStr)
if ~exist(pathStr, 'dir')
    mkdir(pathStr);
end
end
