function cfg = get_comsol_in_loop_ga_optimization_champion_config_v1()
%GET_COMSOL_IN_LOOP_GA_OPTIMIZATION_CHAMPION_CONFIG_V1
% Champion-funnel stage 4: all-in exploitation on the strongest surviving basin.

cfg = get_comsol_in_loop_ga_optimization_funnel_probe_config_v1();
cfg.gaId = 'comsol_in_loop_ga_optimization_champion_v1';
cfg = apply_real_ga_output_layout_v1(cfg, fullfile(cfg.rootDir, 'data', 'comsol_batch', cfg.gaId));

cfg.previousGaId = 'comsol_in_loop_ga_optimization_duel_v1';
cfg.previousOutDir = fullfile(cfg.rootDir, 'data', 'comsol_batch', cfg.previousGaId);
cfg.previousShapeSummaryCsv = fullfile(cfg.previousOutDir, 'comsol_in_loop_ga_shape_summary.csv');
cfg.previousSearchSummaryCsv = fullfile(cfg.previousOutDir, 'ga_search_summary_v1.csv');
cfg.previousBestCandidatesCsv = fullfile(cfg.previousOutDir, 'ga_best_candidates_v1.csv');
cfg.previousSeedSelectionCsv = fullfile(cfg.previousOutDir, 'ga_seed_selection_v1.csv');
cfg.previousTopKSeeds = 1;
cfg.previousMinMeanGainHz = 0.0;
cfg.previousMinPositiveRate = 0.0;
cfg.previousMinSolveSuccessCount = 1;

cfg.forceSeedShapeIds = cellstr(select_optimization_stage_seed_ids_v1( ...
    cfg.previousShapeSummaryCsv, ...
    cfg.previousTopKSeeds, ...
    cfg.previousMinMeanGainHz, ...
    cfg.previousMinPositiveRate, ...
    cfg.previousMinSolveSuccessCount));
cfg.topKSeeds = numel(cfg.forceSeedShapeIds);

ensure_dir(cfg.outDir);
ensure_dir(cfg.tbl1Dir);
ensure_dir(cfg.logsDir);
ensure_dir(cfg.plotDir);
if cfg.saveModel
    ensure_dir(cfg.modelsDir);
end
cfg.stageSeedScoredCsv = fullfile(cfg.outDir, 'ga_stage_seed_selection_v1.csv');
cfg.seedScoredCsv = build_optimization_stage_seed_csv_v1( ...
    cfg.previousSeedSelectionCsv, ...
    cfg.previousBestCandidatesCsv, ...
    string(cfg.forceSeedShapeIds(:)), ...
    cfg.stageSeedScoredCsv);
cfg.seedScoredSignatureOverride = build_stage_seed_signature(cfg);

cfg.populationSize = 16;
cfg.generations = 17;
cfg.eliteCount = 3;
cfg.mutationRate = 0.20;
cfg.mutationScale = 0.08;
cfg.topCandidatesPerSeedExport = 5;

% Keep room for a last large move inside the champion basin instead of
% shrinking too early and getting trapped below the true basin peak.
cfg.localHalfWidths = struct( ...
    'a1', 0.0300, ...
    'a2', 0.0320, ...
    'b1', 0.0120, ...
    'b2', 0.0180, ...
    'a3', 0.0240, ...
    'b3', 0.0240, ...
    'a4', 0.0160, ...
    'b4', 0.0160, ...
    'a5', 0.0100, ...
    'b5', 0.0100, ...
    'r0', 0.00080 ...
);

signatureParts = [ ...
    get_real_ga_base_signature_parts_v1(cfg), ...
    { ...
    'optimization_mode=champion', ...
    ['previous_ga=' cfg.previousGaId], ...
    ['previous_shape_summary=' file_signature_v1(cfg.previousShapeSummaryCsv)], ...
    ['previous_search_summary=' file_signature_v1(cfg.previousSearchSummaryCsv)], ...
    ['previous_best_candidates=' file_signature_v1(cfg.previousBestCandidatesCsv)], ...
    ['previous_seed_selection=' file_signature_v1(cfg.previousSeedSelectionCsv)], ...
    ['previous_top_k=' num2str(cfg.previousTopKSeeds)], ...
    'funnel_budget=1x16x17' ...
    } ...
];
cfg.configSignature = join_signature_parts_v1(signatureParts);
end

function ensure_dir(pathStr)
if ~exist(pathStr, 'dir')
    mkdir(pathStr);
end
end

function sig = build_stage_seed_signature(cfg)
sig = join_signature_parts_v1({ ...
    'stage_seed_builder=v1', ...
    ['stage_seed_csv=' cfg.stageSeedScoredCsv], ...
    ['survivors=' strjoin(string(cfg.forceSeedShapeIds), ',')], ...
    ['previous_seed_selection=' file_signature_v1(cfg.previousSeedSelectionCsv)], ...
    ['previous_best_candidates=' file_signature_v1(cfg.previousBestCandidatesCsv)] ...
    });
end
