function cfg = get_comsol_in_loop_ga_optimization_champion_local_config_v3()
%GET_COMSOL_IN_LOOP_GA_OPTIMIZATION_CHAMPION_LOCAL_CONFIG_V3
% Champion v3 replaces the last-stage GA with a local trust-region style
% search that uses predictor-guided prescreening before COMSOL truth calls.

cfg = get_comsol_in_loop_ga_optimization_funnel_probe_config_v1();
cfg.gaId = 'comsol_in_loop_ga_optimization_champion_v3';
cfg = apply_real_ga_output_layout_v1(cfg, fullfile(cfg.rootDir, 'data', 'comsol_batch', cfg.gaId));

cfg.previousGaId = 'comsol_in_loop_ga_optimization_duel_v2';
cfg.previousOutDir = fullfile(cfg.rootDir, 'data', 'comsol_batch', cfg.previousGaId);
cfg.previousShapeSummaryCsv = fullfile(cfg.previousOutDir, 'comsol_in_loop_ga_shape_summary.csv');
cfg.previousSearchSummaryCsv = fullfile(cfg.previousOutDir, 'ga_search_summary_v1.csv');
cfg.previousBestCandidatesCsv = fullfile(cfg.previousOutDir, 'ga_best_candidates_v1.csv');
cfg.previousSeedSelectionCsv = fullfile(cfg.previousOutDir, 'ga_seed_selection_v1.csv');

gate = struct();
gate.topKSeeds = 1;
gate.minMeanGainHz = 0.0;
gate.minPositiveRate = 0.0;
gate.minSolveSuccessCount = 1;
gate.enableNearTiePromotion = true;
gate.nearTieKeepCount = 2;
gate.nearTieGapHz = 0.5;
gate.nearTieGapRel = 0.02;

cfg.forceSeedShapeIds = cellstr(select_optimization_stage_seed_ids_v2(cfg.previousShapeSummaryCsv, gate));
cfg.topKSeeds = numel(cfg.forceSeedShapeIds);

ensure_dir(cfg.outDir);
ensure_dir(cfg.tbl1Dir);
ensure_dir(cfg.logsDir);
ensure_dir(cfg.plotDir);
if cfg.saveModel
    ensure_dir(cfg.modelsDir);
end
cfg.stageSeedScoredCsv = fullfile(cfg.outDir, 'ga_stage_seed_selection_v1.csv');
cfg.seedScoredCsv = build_optimization_stage_seed_csv_v1( ...
    cfg.previousSeedSelectionCsv, ...
    cfg.previousBestCandidatesCsv, ...
    string(cfg.forceSeedShapeIds(:)), ...
    cfg.stageSeedScoredCsv);
cfg.seedScoredSignatureOverride = build_stage_seed_signature(cfg);

cfg.totalEvalBudget = 272;
cfg.evalsPerIteration = 4;
cfg.proposalsPerIteration = 48;
cfg.iterationsPerSeed = max(1, floor(cfg.totalEvalBudget / max(cfg.topKSeeds, 1) / cfg.evalsPerIteration));
cfg.populationSize = cfg.evalsPerIteration;
cfg.generations = cfg.iterationsPerSeed;
cfg.eliteCount = 1;
cfg.mutationRate = 0.0;
cfg.mutationScale = 0.0;
cfg.topCandidatesPerSeedExport = 8;

cfg.minImprovementHz = 0.05;
cfg.expandFactor = 1.08;
cfg.shrinkFactor = 0.72;
cfg.reexpandFactor = 1.20;
cfg.stallIterationsBeforeReexpand = 3;

cfg.basinHalfWidths = struct( ...
    'a1', 0.0450, ...
    'a2', 0.0500, ...
    'b1', 0.0180, ...
    'b2', 0.0280, ...
    'a3', 0.0350, ...
    'b3', 0.0350, ...
    'a4', 0.0240, ...
    'b4', 0.0240, ...
    'a5', 0.0150, ...
    'b5', 0.0150, ...
    'r0', 0.00100 ...
);

cfg.localHalfWidths = struct( ...
    'a1', 0.0180, ...
    'a2', 0.0200, ...
    'b1', 0.0080, ...
    'b2', 0.0120, ...
    'a3', 0.0150, ...
    'b3', 0.0150, ...
    'a4', 0.0100, ...
    'b4', 0.0100, ...
    'a5', 0.0080, ...
    'b5', 0.0080, ...
    'r0', 0.00045 ...
);

cfg.prescreenPython = 'python';
cfg.prescreenScript = fullfile(cfg.rootDir, 'stage3_training', 'score_optimization_candidates_v1.py');
cfg.prescreenInputDir = fullfile(cfg.logsDir, 'prescreen_inputs');
cfg.prescreenOutputDir = fullfile(cfg.logsDir, 'prescreen_outputs');
ensure_dir(cfg.prescreenInputDir);
ensure_dir(cfg.prescreenOutputDir);

signatureParts = [ ...
    get_real_ga_base_signature_parts_v1(cfg), ...
    { ...
    'optimization_mode=champion_local_v3', ...
    ['previous_ga=' cfg.previousGaId], ...
    ['previous_shape_summary=' file_signature_v1(cfg.previousShapeSummaryCsv)], ...
    ['previous_search_summary=' file_signature_v1(cfg.previousSearchSummaryCsv)], ...
    ['previous_best_candidates=' file_signature_v1(cfg.previousBestCandidatesCsv)], ...
    ['previous_seed_selection=' file_signature_v1(cfg.previousSeedSelectionCsv)], ...
    ['eval_budget=' num2str(cfg.totalEvalBudget)], ...
    ['evals_per_iteration=' num2str(cfg.evalsPerIteration)], ...
    ['proposals_per_iteration=' num2str(cfg.proposalsPerIteration)], ...
    ['iterations_per_seed=' num2str(cfg.iterationsPerSeed)], ...
    ['prescreen_script=' file_signature_v1(cfg.prescreenScript)], ...
    'champion_mode=local_trust_region_with_prescreen' ...
    } ...
];
cfg.configSignature = join_signature_parts_v1(signatureParts);
end

function ensure_dir(pathStr)
if ~exist(pathStr, 'dir')
    mkdir(pathStr);
end
end

function sig = build_stage_seed_signature(cfg)
sig = join_signature_parts_v1({ ...
    'stage_seed_builder=v3_local', ...
    ['stage_seed_csv=' cfg.stageSeedScoredCsv], ...
    ['survivors=' strjoin(string(cfg.forceSeedShapeIds), ',')], ...
    ['previous_seed_selection=' file_signature_v1(cfg.previousSeedSelectionCsv)], ...
    ['previous_best_candidates=' file_signature_v1(cfg.previousBestCandidatesCsv)] ...
    });
end
