function cfg = get_comsol_in_loop_ga_optimization_duel_config_v4()
%GET_COMSOL_IN_LOOP_GA_OPTIMIZATION_DUEL_CONFIG_V4
% v4 duel keeps v2's wildcard protection because it was the first broadly
% useful fix for not prematurely eliminating high-ceiling basins.

cfg = get_comsol_in_loop_ga_optimization_funnel_probe_config_v4();
cfg.gaId = 'comsol_in_loop_ga_optimization_duel_v4';
cfg = apply_real_ga_output_layout_v1(cfg, fullfile(cfg.rootDir, 'data', 'comsol_batch', cfg.gaId));

cfg.previousGaId = 'comsol_in_loop_ga_optimization_expansion_v4';
cfg.previousOutDir = fullfile(cfg.rootDir, 'data', 'comsol_batch', cfg.previousGaId);
cfg.previousShapeSummaryCsv = fullfile(cfg.previousOutDir, 'comsol_in_loop_ga_shape_summary.csv');
cfg.previousSearchSummaryCsv = fullfile(cfg.previousOutDir, 'ga_search_summary_v1.csv');
cfg.previousBestCandidatesCsv = fullfile(cfg.previousOutDir, 'ga_best_candidates_v1.csv');
cfg.previousSeedSelectionCsv = fullfile(cfg.previousOutDir, 'ga_seed_selection_v1.csv');

gate = struct();
gate.topKSeeds = 2;
gate.minMeanGainHz = 0.0;
gate.minPositiveRate = 0.0;
gate.minSolveSuccessCount = 1;
gate.wildcardMaxCount = 1;
gate.wildcardReferenceRank = 2;
gate.wildcardGapHz = 1.5;
gate.wildcardGapRel = 0.05;

cfg.forceSeedShapeIds = cellstr(select_optimization_stage_seed_ids_v2(cfg.previousShapeSummaryCsv, gate));
cfg.topKSeeds = numel(cfg.forceSeedShapeIds);

ensure_dir(cfg.outDir);
ensure_dir(cfg.tbl1Dir);
ensure_dir(cfg.logsDir);
ensure_dir(cfg.plotDir);
if cfg.saveModel
    ensure_dir(cfg.modelsDir);
end
cfg.stageSeedScoredCsv = fullfile(cfg.outDir, 'ga_stage_seed_selection_v1.csv');
cfg.seedScoredCsv = build_optimization_stage_seed_csv_v1( ...
    cfg.previousSeedSelectionCsv, ...
    cfg.previousBestCandidatesCsv, ...
    string(cfg.forceSeedShapeIds(:)), ...
    cfg.stageSeedScoredCsv);
cfg.seedScoredSignatureOverride = build_stage_seed_signature(cfg);

cfg.generations = 7;
if cfg.topKSeeds >= 3
    cfg.populationSize = 8;
    cfg.eliteCount = 2;
    cfg.topCandidatesPerSeedExport = 3;
else
    cfg.populationSize = 12;
    cfg.eliteCount = 2;
    cfg.topCandidatesPerSeedExport = 4;
end
cfg.mutationRate = 0.22;
cfg.mutationScale = 0.10;

cfg.localHalfWidths = struct( ...
    'a1', 0.0250, ...
    'a2', 0.0300, ...
    'b1', 0.0120, ...
    'b2', 0.0160, ...
    'a3', 0.0220, ...
    'b3', 0.0220, ...
    'a4', 0.0150, ...
    'b4', 0.0150, ...
    'a5', 0.0100, ...
    'b5', 0.0100, ...
    'r0', 0.00075 ...
);

signatureParts = [ ...
    get_real_ga_base_signature_parts_v1(cfg), ...
    { ...
    'optimization_mode=duel_v4', ...
    ['previous_ga=' cfg.previousGaId], ...
    ['previous_shape_summary=' file_signature_v1(cfg.previousShapeSummaryCsv)], ...
    ['previous_search_summary=' file_signature_v1(cfg.previousSearchSummaryCsv)], ...
    ['previous_best_candidates=' file_signature_v1(cfg.previousBestCandidatesCsv)], ...
    ['previous_seed_selection=' file_signature_v1(cfg.previousSeedSelectionCsv)], ...
    ['wildcard_gap_hz=' num2str(gate.wildcardGapHz, '%.12g')], ...
    ['wildcard_gap_rel=' num2str(gate.wildcardGapRel, '%.12g')], ...
    ['population=' num2str(cfg.populationSize)], ...
    'funnel_budget_v4=adaptive_duel' ...
    } ...
];
cfg.configSignature = join_signature_parts_v1(signatureParts);
end

function ensure_dir(pathStr)
if ~exist(pathStr, 'dir')
    mkdir(pathStr);
end
end

function sig = build_stage_seed_signature(cfg)
sig = join_signature_parts_v1({ ...
    'stage_seed_builder=v4', ...
    ['stage_seed_csv=' cfg.stageSeedScoredCsv], ...
    ['survivors=' strjoin(string(cfg.forceSeedShapeIds), ',')], ...
    ['previous_seed_selection=' file_signature_v1(cfg.previousSeedSelectionCsv)], ...
    ['previous_best_candidates=' file_signature_v1(cfg.previousBestCandidatesCsv)] ...
    });
end
