function parts = get_real_ga_base_signature_parts_v1(cfg)
%GET_REAL_GA_BASE_SIGNATURE_PARTS_V1 Shared base signature parts for real-GA configs.

seedScoredSignature = file_signature_v1(cfg.seedScoredCsv);
if isfield(cfg, 'seedScoredSignatureOverride') && strlength(string(cfg.seedScoredSignatureOverride)) > 0
    seedScoredSignature = char(string(cfg.seedScoredSignatureOverride));
end

generationCount = NaN;
if isfield(cfg, 'maxGenerations') && ~isempty(cfg.maxGenerations)
    generationCount = double(cfg.maxGenerations);
elseif isfield(cfg, 'generations') && ~isempty(cfg.generations)
    generationCount = double(cfg.generations);
end

parts = { ...
    cfg.gaId, ...
    ['seed_scored_csv=' seedScoredSignature], ...
    ['seed_point=' cfg.seedPointId], ...
    ['seed_whitelist=' file_signature_v1(cfg.seedWhitelistJson)], ...
    ['force_seed_shapes=' strjoin(string(cfg.forceSeedShapeIds), ',')], ...
    ['top_k=' num2str(cfg.topKSeeds)], ...
    ['search_bounds_mode=' char(string(cfg.searchBoundsMode))], ...
    ['seed_sort_fields=' strjoin(string(cfg.seedSortFields), ',')], ...
    ['seed_sort_directions=' strjoin(string(cfg.seedSortDirections), ',')], ...
    ['population=' num2str(cfg.populationSize)], ...
    ['generations=' num2str(generationCount)], ...
    ['elite=' num2str(cfg.eliteCount)], ...
    ['mutation_rate=' num2str(cfg.mutationRate, '%.12g')], ...
    ['mutation_scale=' num2str(cfg.mutationScale, '%.12g')], ...
    ['distance_penalty=' num2str(cfg.distancePenaltyWeight, '%.12g')], ...
    ['random_seed=' num2str(cfg.randomSeed)], ...
    ['active_params=' strjoin(cfg.activeParamNames, ',')], ...
    ['fixed_gap_band=' num2str(cfg.fixedGapBand)], ...
    ['material_case=' cfg.materialCase] ...
};
end
